"""initial_migration_place_table

Revision ID: ad4fe0960464
Revises: 
Create Date: 2026-06-30 08:02:40.207107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad4fe0960464'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('places', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='goride')
    op.alter_column('places', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               schema='goride')
    op.alter_column('places', 'display_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='goride')
    op.alter_column('places', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               schema='goride')
    op.alter_column('places', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               schema='goride')
    op.alter_column('places', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='goride')
    op.alter_column('places', 'district',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='goride')
    op.alter_column('places', 'state',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='goride')
    op.alter_column('places', 'country',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='goride')
    op.alter_column('places', 'search_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='goride')
    op.alter_column('places', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='goride')
    op.alter_column('places', 'place_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='goride')
    op.alter_column('places', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='goride')
    op.create_index(op.f('ix_goride_places_id'), 'places', ['id'], unique=False, schema='goride')
    op.drop_column('places', 'search_count', schema='goride')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('search_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True), schema='goride')
    op.drop_index(op.f('ix_goride_places_id'), table_name='places', schema='goride')
    op.alter_column('places', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='goride')
    op.alter_column('places', 'place_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='goride')
    op.alter_column('places', 'source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='goride')
    op.alter_column('places', 'search_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='goride')
    op.alter_column('places', 'country',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='goride')
    op.alter_column('places', 'state',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='goride')
    op.alter_column('places', 'district',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='goride')
    op.alter_column('places', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='goride')
    op.alter_column('places', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               schema='goride')
    op.alter_column('places', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               schema='goride')
    op.alter_column('places', 'display_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='goride')
    op.alter_column('places', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='goride')
    op.alter_column('places', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='goride')
    # ### end Alembic commands ###
