"""add_search_count_and_indexes

Revision ID: ad90996d8bcc
Revises: 9d59a41c14b3
Create Date: 2026-06-30 09:17:36.738853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad90996d8bcc'
down_revision: Union[str, Sequence[str], None] = '9d59a41c14b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')
    op.add_column('places', sa.Column('search_count', sa.Integer(), server_default='0', nullable=False), schema='goride')
    op.create_index('ix_places_category', 'places', ['category'], unique=False, schema='goride')
    op.create_index('ix_places_district', 'places', ['district'], unique=False, schema='goride')
    op.create_index('ix_places_pincode', 'places', ['pincode'], unique=False, schema='goride')
    op.create_index('ix_places_search_key_trgm', 'places', ['search_key'], unique=False, schema='goride', postgresql_ops={'search_key': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_places_search_key_trgm', table_name='places', schema='goride', postgresql_ops={'search_key': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index('ix_places_pincode', table_name='places', schema='goride')
    op.drop_index('ix_places_district', table_name='places', schema='goride')
    op.drop_index('ix_places_category', table_name='places', schema='goride')
    op.drop_column('places', 'search_count', schema='goride')
    # ### end Alembic commands ###
